spring.application.name=school
spring.datasource.url= jdbc:postgresql://localhost:5432/school
spring.datasource.username=school
spring.datasource.password=123

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
